### ISSUE TITLE
Cant configure plugin

### ISSUE THREAD

**Issue by wallyt99** [KEGustafsson/signalk-aisstream#1]
Thanks for this amazing tool.  I'm excited to try it!  However I can't seem to install it properly or gain access to a configuration screen!
When I click install in the Signal  K appstore, it shows as 'installed' at the top, however upon restart it is no longer 'installed'.  Additionally no configuration options appear in the plugins configuration section.

**Comment by KEGustafsson** [comment]
Fixed in [v0.3.0](https://github.com/KEGustafsson/signalk-aisstream/commit/f4c0e12b534b219dbdd9da62587334140c60ba24), which is now released also to npmjs [signalk-aisstream](https://www.npmjs.com/package/signalk-aisstream)

**Comment by KEGustafsson** [comment]
Fixed in [v0.3.0](https://github.com/KEGustafsson/signalk-aisstream/commit/f4c0e12b534b219dbdd9da62587334140c60ba24), which is now released also to npmjs [signalk-aisstream](https://www.npmjs.com/package/signalk-aisstream)
