### ISSUE TITLE
signalk aisstream not receiving data

### ISSUE THREAD

**Issue by xboluda** [KEGustafsson/signalk-aisstream#4]
Good morning,
Good plugin for improving AIS range when still have internet.
INstalled signalk-aistream into a signalk fresh version and checking the logs I can see signalk-aisstream is started, but pulls no data. Looking at the logs, I only see this one from signalk-aistream.
Nov 27 14:22:56 2024-11-27T13:22:56.518Z signalk-aisstream AisStream Plugin Started

Tested my aisstream API-key with node-ned and works fine.

My Node version is 18.20.5 and npm 10.9.1. Maybe this is an issue?

What I'm  missing? any connection to include in signalk?
Thanks

**Comment by KEGustafsson** [comment]
Just tested clean install and working fine. Can you provide log. After plugin start wait ~1min. Location data need to be available too.

**Comment by xboluda** [comment]
Hi,
My settings are as follow:

￼


Attached the loggin file and below screenshot.

Vessel possition is taken via fixed position and also via NMEA from gps, but makes no difference.

￼

￼
Regadrs,
Xavier

**Comment by KEGustafsson** [comment]
Can you upload attachment or screen captures again. There seems to be some issues with those.

**Comment by xboluda** [comment]
Attached
￼

**Comment by KEGustafsson** [comment]
Thank You finding this typo error from code!
Definitely it should be &&

**Comment by KEGustafsson** [comment]
fixed with https://github.com/KEGustafsson/signalk-aisstream/commit/349a4f0ddcd73c3c58ed36ee731fcbcbb010b4a6
